[package]
name = "gl_bindings"
version = "0.1.0"
authors = ["CJ Burkey <cjburkey01@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
gl_generator = "0.14.0"

[features]
debug = []
